apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "paws-recommendation.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "paws-recommendation.name" . }}
    helm.sh/chart: {{ include "paws-recommendation.chart" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "paws-recommendation.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "paws-recommendation.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
